### ISSUE TITLE
Unable to seed database due to missing gem requirement

### ISSUE THREAD

**Issue by agrare** [Autosde/manageiq-providers-autosde#1]
Typhoeus needs to be called out as a dependency in the `manageiq-providers-autosde.gemspec`

```
LoadError: No such file to load -- typhoeus.rb
/home/grare/adam/.gems/2.7.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:291:in `require'
/home/grare/adam/.gems/2.7.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:291:in `block in require'
/home/grare/adam/.gems/2.7.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:255:in `block in load_dependency'
/home/grare/adam/.gems/2.7.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:661:in `new_constants_in'
/home/grare/adam/.gems/2.7.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:255:in `load_dependency'
/home/grare/adam/.gems/2.7.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:291:in `require'
/home/grare/adam/src/manageiq/manageiq-providers-autosde/app/models/manageiq/providers/autosde/storage_manager/openapi_client/generated/lib/openapi_client/api_client.rb:17:in `<top (required)>'
/home/grare/adam/src/manageiq/manageiq-providers-autosde/app/models/manageiq/providers/autosde/storage_manager/openapi_client/generated/lib/openapi_client.rb:14:in `require_relative'
/home/grare/adam/src/manageiq/manageiq-providers-autosde/app/models/manageiq/providers/autosde/storage_manager/openapi_client/generated/lib/openapi_client.rb:14:in `<top (required)>'
/home/grare/adam/src/manageiq/manageiq-providers-autosde/app/models/manageiq/providers/autosde/storage_manager/autosde_client.rb:1:in `require_relative'
/home/grare/adam/src/manageiq/manageiq-providers-autosde/app/models/manageiq/providers/autosde/storage_manager/autosde_client.rb:1:in `<top (required)>'
```

**Comment by agrare** [comment]
This was hit while running `rails db:drop db:create db:migrate db:seed`, with the `provider-basics` branch
